name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get github.com/vkuznet/x509proxy
        go get github.com/buger/jsonparser
        go get github.com/pkg/profile
        go get github.com/stretchr/testify
        go get github.com/go-stomp/stomp
        go get github.com/gizak/termui/v3
        go get github.com/gizak/termui/v3/widgets
        go get github.com/elastic/go-elasticsearch
        go get github.com/nats-io/nats.go
        go get github.com/dmwm/cmsauth
        go get github.com/sirupsen/logrus
        go get github.com/prometheus/client_golang/prometheus
        go get github.com/prometheus/common/log
        go get github.com/prometheus/common/version
        go get github.com/shirou/gopsutil/cpu
        go get github.com/shirou/gopsutil/mem
        go get github.com/shirou/gopsutil/load
        go get github.com/shirou/gopsutil/process

    - name: Build
      run: |
        go build -o monit src/go/MONIT/monit.go
        go build -o alert src/go/MONIT/alert.go
        go build -o annotationManager src/go/MONIT/annotationManager.go
        go build -o datasources src/go/MONIT/datasources.go
        go build -o ggus_alerting src/go/MONIT/ggus_alerting.go
        go build -o ggus_parser src/go/MONIT/ggus_parser.go
        go build -o intelligence src/go/MONIT/intelligence.go
        go build -o ssb_alerting src/go/MONIT/ssb_alerting.go
        go build -o dbs_vm src/go/NATS/dbs_vm.go
        go build -o nats-exitcodes-termui src/go/NATS/nats-exitcodes-termui.go
        go build -o nats-pub src/go/NATS/nats-pub.go
        go build -o nats-sub src/go/NATS/nats-sub.go
        mkdir cmsmon-tools
        mv monit alert annotationManager datasources ggus_alerting \
          ggus_parser intelligence ssb_alerting dbs_vm nats-exitcodes-termui nats-pub nats-sub \
          cmsmon-tools
        tar cfz cmsmon-tools.tar.gz cmsmon-tools

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binaries
      id: upload-cmsmon-tools
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cmsmon-tools.tar.gz
        asset_name: cmsmon-tools.tar.gz
        asset_content_type: application/octet-stream
