# Ref: https://github.com/dmwm/dbs2go/blob/master/.github/workflows/build.yml
name: Build

on:
  push:
    tags:
      - 'go-*.*.*'
    paths-ignore:
      - 'src/go/rucio-dataset-mon-go/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir cmsmon-tools
          cd src/go/MONIT
          CGO_ENABLED=0 go build -ldflags "-s -w -extldflags '-static'" -o monit monit.go
          CGO_ENABLED=0 go build -ldflags "-s -w -extldflags '-static'" -o alert alert.go
          CGO_ENABLED=0 go build -ldflags "-s -w -extldflags '-static'" -o annotationManager annotationManager.go
          CGO_ENABLED=0 go build -ldflags "-s -w -extldflags '-static'" -o datasources datasources.go
          CGO_ENABLED=0 go build -ldflags "-s -w -extldflags '-static'" -o es_exporter es_exporter.go
          mv monit alert annotationManager datasources es_exporter ../../../cmsmon-tools
          cd ../NATS
          CGO_ENABLED=0 go build -ldflags "-s -w -extldflags '-static'" -o dbs_vm dbs_vm.go
          CGO_ENABLED=0 go build -ldflags "-s -w -extldflags '-static'" -o nats-pub nats-pub.go
          CGO_ENABLED=0 go build -ldflags "-s -w -extldflags '-static'" -o nats-sub nats-sub.go
          mv dbs_vm nats-pub nats-sub ../../../cmsmon-tools
          cd ../../../
          tar cfz cmsmon-tools.tar.gz cmsmon-tools

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload binaries
        id: upload-cmsmon-tools
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cmsmon-tools.tar.gz
          asset_name: cmsmon-tools.tar.gz
          asset_content_type: application/octet-stream
