# Ref: https://github.com/dmwm/dbs2go/blob/master/.github/workflows/build.yml

name: Build

on:
  push:
    tags:
      - 'sqoop-*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get git tag
        id: get_tag
        run: echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Get sqoop Dockerfile
        run: |
          curl -ksLO https://raw.githubusercontent.com/dmwm/CMSKubernetes/master/docker/sqoop/Dockerfile

      - name: Login to registry.cern.ch
        uses: docker/login-action@v3
        with:
          registry: registry.cern.ch
          username: ${{ secrets.CERN_LOGIN }}
          password: ${{ secrets.CERN_TOKEN }}

      - name: Publish sqoop image to registry.cern.ch
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          build-args: |
            CMSMON_TAG=${{ steps.get_tag.outputs.tag }}
          tags: registry.cern.ch/cmsmonitoring/sqoop:${{ steps.get_tag.outputs.tag }}, registry.cern.ch/cmsmonitoring/sqoop:latest
