name: Continuous integration testing

on: [pull_request, push]

jobs:
  test_json:
  
    runs-on: ubuntu-latest
  
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: check valid json
        run: |
          echo "Checking valid json..."
          shopt -s globstar
          ls **/*.json
          ls **/*.json >/dev/null && for j in **/*.json; do python -mjson.tool "$j" > /dev/null || (echo "INVALID $j" >&2; 1>foo ); done
          #'[[ !  -f "foo" ]]'

  test_yaml:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: check valid yaml
        run: |
          echo "Checking valid yaml..."
          shopt -s globstar
          echo "Checking valid yaml..."



  
#shopt -s globstar
#ls **/*.json >/dev/null && for j in **/*.json; do python -mjson.tool "$j" > /dev/null || (echo "INVALID $j" >&2; 1>foo ); done
#      '[[ !  -f "foo" ]]'


#      #shopt -s globstar
#ls **/*.yaml >/dev/null && for j in **/*.yaml; do python -c 'import yaml, sys; print(yaml.safe_load(sys.stdin))' <  $j > /dev/null || (echo "INVALID $j" >&2; 1>foo1 ); done
#      '[[ !  -f "foo1" ]]'
